config/routes.rb
Rails.application.routes.draw do


  devise_for :users, 
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' },
    controllers: { registrations: 'registrations' }
  resources :users

 	resources :posts do
 		resources :comments, only: [:create, :destroy]
	 end

	root "posts#index"

 	get "/about" => "pages#about"

	as :user do
  	get 'login' => 'devise/sessions#new'
    get 'logout' => 'devise/sessions#destroy'
    get 'sign_up' => 'users#create'
    get 'sign_up_authorised' => 'devise/registrations#new'
  end
 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.role=="admin"
      can :manage, :all
    elsif user.role=="moderator"
      can :read, [Comment, Post]
      can :update, Comment
    else
      can :read, User, id: user.id
      can :read, [Comment, Post]
      can [:create, :update, :destroy], Comment, id: user.id
    end

  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :name, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

	scope :with_tag, -> (tag) { where("tags like ?", "%#{tag}%")}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable      

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, alert: exception.message
  end

  WillPaginate.per_page = 2
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comments_params)
		@comment.user = current_user
		@comment.save

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

	private

	def comments_params
		params.require(:comment).permit(:name, :body, :confirmed)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]

	def index
		if params[:q]
			search_term = params[:q]
			unless Rails.env.test?
				@posts = Post.with_tag(search_term).page(params[:page])
			end
		else
		@posts = Post.page(params[:page]).order("created_at DESC")
		end
	end

	def new
		@post = Post.new
		authorize! :new, @post
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
		authorize! :edit, @post
	end

	def update
		@post = Post.find(params[:id])
		
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
		authorize! :update, @post
	end

	def create
		@user = current_user
		@post = @user.posts.build(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
		authorize! :create, @post
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy

		redirect_to root_path
		authorize! :destroy, post
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :tags)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
    authorize! :create, @user
  end

  def new
    @user = User.new
    authorize! :new, @user
  end

  def index
    @users = User.all
    authorize! :index, @user
  end

  def show
    @user = User.find(params[:id])
    authorize! :show, @user
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
    authorize! :update, @user
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def destroy
    user = User.find(params[:id])
    deleted_user = user.name
    user.destroy
    redirect_to users_path, alert: "Successfully deleted user: #{deleted_user}."
    authorize! :destroy, user
  end

  private

  def user_params
    params.require(:user).permit(:role, :name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title

		app_name = t(:app_name)
		action = t("titles.#{controller_name}.#{action_name}", default: '')
		action += " #{object_name}" if object_name.present?
		action += " #{post_title}" if post_title.present?
		action += " - " if action.present?
		"#{action} #{app_name}"
		
	end

	def object_name

		assigns[controller_name.singularize].name rescue nil

	end

	def post_title

		assigns[controller_name.singularize].title rescue nil

	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="commnet_name"><strong><%= comment.name %></strong> <span class="comment_time"><i><%= time_ago_in_words(comment.created_at) %> ago</i></span></p>
		
		<p class="comment_body"><%= comment.body %></p>
	</div>
	<% if can? :destroy, @comment %>
	<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class:"button", data:{confirm: 'Are you sure?'}, class:"btn btn-default pull-right" %></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

	<div class="form-group">
		<%= f.label :name %><br>
		<% if signed_in? %>
			<%= f.text_field :name, value: "#{current_user.name}", class: "form-control" %>
		<% else %>
			<%= f.text_field :name, class: "form-control" %>
		<% end %>
	</div>
	
	<div class="form-group">
		<%= f.label :body %><br>
		<%= f.text_area :body, class: "form-control" %>
	</div>
	
	<%= f.button "Submit", type: "submit", class: "btn btn-default"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= page_title %></title>
	<!-- Unicode -->
	<meta charset="UTF-8">
	<!-- Responsive vieport setting -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<!-- Bootstrap js -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<!-- Styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Google fonts -->
  <%= stylesheet_link_tag 'application' , 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= stylesheet_link_tag 'application' , 'https://fonts.googleapis.com/css?family=Varela+Round' %>
  <!-- Font Awesome! -->
	<script src="https://use.fontawesome.com/16f2b8cc35.js"></script>
	<!-- Web icon -->
	<link rel="shortcut icon" href="https://s3-eu-west-1.amazonaws.com/codestraggler/images/coding_struggler.ico" />
  <!-- js global -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<div class="loggedin">
			<% if signed_in? %>
				<p><%= link_to current_user.email, user_path(current_user.id) %> | <%= link_to "logout", logout_path %></p>
			<% else %>
				<p><%= link_to "login", login_path %> | <%= link_to "sing up", sign_up_authorised_path %></p> 
			<% end %>
		</div>
		<nav>
			<div class="header clearfix">
				<div class="logo pull-left">
					<%= image_tag("https://s3-eu-west-1.amazonaws.com/codestraggler/images/coding_struggler.jpg") %>
				</div>
				<h1 class="pull-left">Code<br>Struggler</h1>
			</div>
			<div class="nav-bar navbar-inverse clearfix">
				<ul class="navigation">
					<li><%= link_to "Blog", root_path %></li>
					<!--<li><a>Playground</a></li> in construction-->
					<li><%= link_to "About", about_path %></li>
					<li><a>Contact</a></li>
				</ul>
				<%= form_tag("/posts", method: "get") do %>	
					<%= search_field_tag :q, nil, class: "search", placeholder: "Search" %>
					<%= button_tag nil, type: "submit", class: "search" do %>
						<span class="glyphicon glyphicon-search"></span>
					<% end %>
				<% end %>
			</div>
		</nav>
		<main>
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class:"alert") %>
			<% end %>
			<!-- all posts sorted by date -->
			<%= yield %>
		</main>
		<footer>
			<p class="copyright">&copy; 2016 All rightes reserved</p>
		</footer>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="page_wrapper">
	<div class="row">
		<div class="col-xs-12 col-sm-3">
			<div id="profile_image">
				<%= image_tag("https://s3-eu-west-1.amazonaws.com/codestraggler/images/profile.jpg") %>
			</div>
		</div>
		<div class="col-xs-12 col-sm-8 col-sm-offset-1">
		<h1>Hiya! You recognise this face coz I follow you to work <strong>every</strong> morning!</h1><br>
		<p>Yeah, I know.<br><br>Anyways, let's get some numbers out of the way, so I can be measured up correctly. Born in 1985, on a rainy Monday afternoon. A group of fine-feathered pigeons, were pecking on some nutritious twigs, outside a fallen ranger's hut, in the middle of a forest. Meanwhile I was being delivered to this world in a hospital, in a town, in northern Poland. Rumor has it, that you leave that place sicker than when arrived...also there was something about dead bodies in black bags, but I can't remember the saying exactly. Anyway, a <span class="label label-default">grim place</span> in a constant struggle between life and death, but so is any hospital for that matter.<br><br>Right, so we've established I was born.<br><br>I don't follow you to work every day, by the way. I only do it to that pie shop round the corner from that pub, then I stare via my phone zooming in on you as distance between us becomes increasingly more unbearably distant. Yes. Yes.</p>
		</div>
</div>

app/views/posts/_form.html.erb
<div class="form_wrapper">

	<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%=pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="form-group">
			<%= f.label :title %> <br>
			<%= f.text_field :title, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :body %> <br>
			<%= f.text_area :body, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :tags %> <br>
			<%= f.text_area :tags, class: "form-control" %>
		</div>

		<%= f.button "Submit", type: "submit", class: "btn btn-default"%>

	<% end %>

</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="actions">
	<% if can? :manage, Post %>
		<%= link_to "Add Post", new_post_path, class: "btn btn-default add_post" %>
	<% end %>
</div>
<% @posts.each do |post| %>
	<div class="post_wrapper">

		<div class="post_title">
			<h2><%= post.title %></h2>
		</div>

		<div class="post_info">
			<p class="when_posted"><%= post.created_at.strftime("%B, %d, %Y")%></p>
			<p class="tags"><% post.tags.split(" ").each do |tag| %>
				<span class="label label-default"><%= tag %></span> 
			<% end %>
		</div>

		<div class="post_preview">
			<p><%= truncate(post.body, length: 300) %></p>
		</div>

		<div class="post_footer clearfix">

			<div class="buttons">
			  <%= link_to '<button class="btn btn-default pull-left">Read More</button>'.html_safe, post %>
			</div>

			<div class="comments_count">
				<a href="#" class="pull-right"><i class="fa fa-commenting-o" aria-hidden="true"></i><%= post.comments.count %></a>
			</div>

		</div> <!-- /post_footer -->

	</div> <!-- /post_wrapper -->
<% end %>
<%= will_paginate @posts %>
<aside>	
	<div class="subscribe_box">
		<header>
			<p>Subscribe for updates</p>
		</header>
		<div class="email_box">
			<input type="email" id="email" placeholder="your@email.address">
			<button class="btn btn-default">Subscribe</button>
		</div>
	</div>
</aside>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%=pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %> <br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %> <br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1><%= @post.title %></h1>
	<p class="date">
		<i>Submitted <%= time_ago_in_words(@post.created_at) %> ago</i>
		 
		<% if can? :update, @post %>
			<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default sides-1" %>
		<% end %>
		
		<% if can? :destroy, @post %>
			<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default sides-1" %>
		<% end %>
	</p>
	<p class="body">
		<%= @post.body %>
	</p>
	<hr>

	<h4 class="pull-right"><%= @post.comments.count %> <i class="fa fa-commenting-o" aria-hidden="true"></i></h4>

	<div id="comments">
		<%= render @post.comments %>
	</div>
	<hr>
	<div id="leave_comment">
		<h3>Leave a comment:</h3>
		<%= render 'comments/form' %>
	</div>

</div>

app/views/users/_form.html.erb
<div class="form_wrapper">
	<%= form_for @user do |f| %>

		<div class="form-group">
			<%= f.label :name %> <br>
			<%= f.text_field :name, class: "form-cotrol" %>
		</div>

		<div class="form-group">
			<%= f.label :email %> <br>
			<%= f.email_field :email, class: "form-cotrol" %>
		</div>

		<div class="form-group">
			<%= f.label :role %> <br>
			<%= f.text_field :role, class: "form-cotrol" %>
		</div>

		<div class="form-group">
			<%= f.label :password %> <br>
			<%= f.password_field :password, class: "form-cotrol" %>
		</div>

		<%= f.button "Submit", type: "submit", class: "btn btn-default"%>

	<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= link_to "Add user", new_user_path, class: "btn btn-default" %>
<% @users.each do |user| %>
	<div class="post_wrapper">
		<div class="post_title">
			<h2>Name: <%= user.name %></h2>
			<h2>Email: <%= user.email %></h2>
			<h2>Role: <%= user.role %></h2>
		</div>
		<div class="actions">
		<%= link_to "Update", edit_user_path(user.id), class: "btn btn-default" %>
		<%= link_to "Delete", user_path(user.id), method: :delete, class: "btn btn-default" %>
		</div>
	</div> <!-- /post_wrapper -->
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="post_wrapper">
	<div class="post_title">
		<h2>Name: <%= @user.name %></h2>
		<h2>Email: <%= @user.email %></h2>
		<h2>Role: <%= @user.role %></h2>
	</div>
	<div class="actions">
		<% if can? :update, @user %>
			<%= link_to "All users", users_path %>
		<% else %>
			<%= link_to "Back", :back %>
		<% end %>
	</div>
</div> <!-- /post_wrapper -->